flow:
  nodes:
    node:
      - id: a
        class: com.yomahub.liteflow.test.component.AComponent
      - id: b
        class: com.yomahub.liteflow.test.component.BComponent
      - id: c
        class: com.yomahub.liteflow.test.component.CComponent
      - id: d
        class: com.yomahub.liteflow.test.component.DComponent
      - id: e
        class: com.yomahub.liteflow.test.component.EComponent
      - id: f
        class: com.yomahub.liteflow.test.component.FComponent
      - id: g
        class: com.yomahub.liteflow.test.component.GComponent
      - id: cond
        class: com.yomahub.liteflow.test.component.CondComponent
  chain:
    - name: chain1
      topo:
        - type: then
          value: 'a,cond(b|d)'
        - type: then
          value: 'e,f,g'
    - name: chain2
      topo:
        - type: then
          value: 'a,c'
        - type: when
          value: 'b,d,e,f,g'
        - type: then
          value: 'c'
    - name: chain3
      topo:
        - type: then
          value: 'a,c,strategy1,g'
    - name: strategy1
      topo:
        - type: then
          value: m(m1|m2|strategy2)
    - name: strategy2
      topo:
        - type: then
          value: 'q,p(p1|p2)'
